### PR TITLE
subscribe to homeassistant/status and not hass/status (default values)

### PR DESCRIPTION
**Pull request by denics**

### CODE REVIEW

**Comment by Sennevds** [comment]
This should be configurable instead of just a different value

**Comment by mmattel** [comment]
@denics I have created a PR, see reference, that incorporates beside my changes also your things but in a way that makes the status configurable and keys fail proof if they are not present. You may want to close this one.

**Comment by mmattel** [comment]
Closing via #173

**Comment by mmattel** [comment]
@Sennevds can you close this PR? It is obsolete with merged #173

**Comment by denics** [comment]
Sorry for reacting late. Thanks for taking into account my suggestions!

**Pull request closed without merging**
