### PR TITLE
Replaced vcgencmd temperature with generic #45

### PR DESCRIPTION
**Pull request by MaxVRAM**
This should allow Pi hardware running non-Pi OS distros to use this project.

### CODE REVIEW

**Comment by Sennevds** [comment]
Could you maybe add a check for the architecture and if it's a rpi still use vcgencmd and if not use /sys/class/thermal/thermal_zone0/temp

**Comment by MaxVRAM** [comment]
That's a good idea. I'll see what I can rustle up.

**Comment by MaxVRAM** [comment]
Check the latest commit.

Also, since we're pulling a bunch of useful information into the OS_DATA object, it might be worth sending some of it in the payload. I'll raise an issue suggestion.

**Comment by scaytrase** [comment]
I can verify this fixes my issues on ubuntu 2020 64-bit with missing vcgencmd

**Comment by scaytrase** [comment]
And still works fine on my 3B+ with raspbian

**Pull request merged**
